version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
      - EMAIL_SERVER_HOST=smtp.gmail.com
      - EMAIL_SERVER_PORT=587
      - EMAIL_SERVER_USER=dev@example.com
      - EMAIL_SERVER_PASSWORD=dev-password
      - EMAIL_FROM=dev@example.com
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    networks:
      - app-network

  # Remove production services for development
  nginx:
    profiles: ["disabled"]
  
  db:
    profiles: ["disabled"]
    
  redis:
    profiles: ["disabled"]
  
  adminer:
    profiles: ["tools"]